// flow-typed signature: faff55f657b80517d8216e7cc59b137c
// flow-typed version: <<STUB>>/recharts_v^2.0.3/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recharts/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/Area' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/Bar' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/Brush' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/CartesianAxis' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/CartesianGrid' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/ErrorBar' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/Line' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/ReferenceArea' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/ReferenceDot' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/ReferenceLine' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/Scatter' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/XAxis' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/YAxis' {
  declare module.exports: any;
}

declare module 'recharts/es6/cartesian/ZAxis' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/AreaChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/BarChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/ComposedChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/FunnelChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/generateCategoricalChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/LineChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/PieChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/RadarChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/RadialBarChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/Sankey' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/ScatterChart' {
  declare module.exports: any;
}

declare module 'recharts/es6/chart/Treemap' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/Cell' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/Customized' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/DefaultLegendContent' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/DefaultTooltipContent' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/Label' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/LabelList' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/Legend' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/ResponsiveContainer' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/Text' {
  declare module.exports: any;
}

declare module 'recharts/es6/component/Tooltip' {
  declare module.exports: any;
}

declare module 'recharts/es6/container/Layer' {
  declare module.exports: any;
}

declare module 'recharts/es6/container/Surface' {
  declare module.exports: any;
}

declare module 'recharts/es6' {
  declare module.exports: any;
}

declare module 'recharts/es6/numberAxis/Funnel' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/Pie' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/PolarAngleAxis' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/PolarGrid' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/PolarRadiusAxis' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/Radar' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/RadialBar' {
  declare module.exports: any;
}

declare module 'recharts/es6/polar/types' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Cross' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Curve' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Dot' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Polygon' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Rectangle' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Sector' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Symbols' {
  declare module.exports: any;
}

declare module 'recharts/es6/shape/Trapezoid' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/CartesianUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/ChartUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/Constants' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/CssPrefixUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/DataUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/DetectReferenceElementsDomain' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/DOMUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/Events' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/Global' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/IfOverflowMatches' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/LogUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/PolarUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/ReactUtils' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/ShallowEqual' {
  declare module.exports: any;
}

declare module 'recharts/es6/util/types' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/Area' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/Bar' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/Brush' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/CartesianAxis' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/CartesianGrid' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/ErrorBar' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/Line' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/ReferenceArea' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/ReferenceDot' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/ReferenceLine' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/Scatter' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/XAxis' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/YAxis' {
  declare module.exports: any;
}

declare module 'recharts/lib/cartesian/ZAxis' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/AreaChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/BarChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/ComposedChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/FunnelChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/generateCategoricalChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/LineChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/PieChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/RadarChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/RadialBarChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/Sankey' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/ScatterChart' {
  declare module.exports: any;
}

declare module 'recharts/lib/chart/Treemap' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/Cell' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/Customized' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/DefaultLegendContent' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/DefaultTooltipContent' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/Label' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/LabelList' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/Legend' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/ResponsiveContainer' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/Text' {
  declare module.exports: any;
}

declare module 'recharts/lib/component/Tooltip' {
  declare module.exports: any;
}

declare module 'recharts/lib/container/Layer' {
  declare module.exports: any;
}

declare module 'recharts/lib/container/Surface' {
  declare module.exports: any;
}

declare module 'recharts/lib' {
  declare module.exports: any;
}

declare module 'recharts/lib/numberAxis/Funnel' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/Pie' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/PolarAngleAxis' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/PolarGrid' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/PolarRadiusAxis' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/Radar' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/RadialBar' {
  declare module.exports: any;
}

declare module 'recharts/lib/polar/types' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Cross' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Curve' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Dot' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Polygon' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Rectangle' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Sector' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Symbols' {
  declare module.exports: any;
}

declare module 'recharts/lib/shape/Trapezoid' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/CartesianUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/ChartUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/Constants' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/CssPrefixUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/DataUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/DetectReferenceElementsDomain' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/DOMUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/Events' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/Global' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/IfOverflowMatches' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/LogUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/PolarUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/ReactUtils' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/ShallowEqual' {
  declare module.exports: any;
}

declare module 'recharts/lib/util/types' {
  declare module.exports: any;
}

declare module 'recharts/umd/Recharts' {
  declare module.exports: any;
}

declare module 'recharts/umd/Recharts.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recharts/demo/webpack.config.js' {
  declare module.exports: $Exports<'recharts/demo/webpack.config'>;
}
declare module 'recharts/es6/cartesian/Area.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/Area'>;
}
declare module 'recharts/es6/cartesian/Bar.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/Bar'>;
}
declare module 'recharts/es6/cartesian/Brush.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/Brush'>;
}
declare module 'recharts/es6/cartesian/CartesianAxis.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/CartesianAxis'>;
}
declare module 'recharts/es6/cartesian/CartesianGrid.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/CartesianGrid'>;
}
declare module 'recharts/es6/cartesian/ErrorBar.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/ErrorBar'>;
}
declare module 'recharts/es6/cartesian/Line.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/Line'>;
}
declare module 'recharts/es6/cartesian/ReferenceArea.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/ReferenceArea'>;
}
declare module 'recharts/es6/cartesian/ReferenceDot.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/ReferenceDot'>;
}
declare module 'recharts/es6/cartesian/ReferenceLine.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/ReferenceLine'>;
}
declare module 'recharts/es6/cartesian/Scatter.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/Scatter'>;
}
declare module 'recharts/es6/cartesian/XAxis.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/XAxis'>;
}
declare module 'recharts/es6/cartesian/YAxis.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/YAxis'>;
}
declare module 'recharts/es6/cartesian/ZAxis.js' {
  declare module.exports: $Exports<'recharts/es6/cartesian/ZAxis'>;
}
declare module 'recharts/es6/chart/AreaChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/AreaChart'>;
}
declare module 'recharts/es6/chart/BarChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/BarChart'>;
}
declare module 'recharts/es6/chart/ComposedChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/ComposedChart'>;
}
declare module 'recharts/es6/chart/FunnelChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/FunnelChart'>;
}
declare module 'recharts/es6/chart/generateCategoricalChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/generateCategoricalChart'>;
}
declare module 'recharts/es6/chart/LineChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/LineChart'>;
}
declare module 'recharts/es6/chart/PieChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/PieChart'>;
}
declare module 'recharts/es6/chart/RadarChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/RadarChart'>;
}
declare module 'recharts/es6/chart/RadialBarChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/RadialBarChart'>;
}
declare module 'recharts/es6/chart/Sankey.js' {
  declare module.exports: $Exports<'recharts/es6/chart/Sankey'>;
}
declare module 'recharts/es6/chart/ScatterChart.js' {
  declare module.exports: $Exports<'recharts/es6/chart/ScatterChart'>;
}
declare module 'recharts/es6/chart/Treemap.js' {
  declare module.exports: $Exports<'recharts/es6/chart/Treemap'>;
}
declare module 'recharts/es6/component/Cell.js' {
  declare module.exports: $Exports<'recharts/es6/component/Cell'>;
}
declare module 'recharts/es6/component/Customized.js' {
  declare module.exports: $Exports<'recharts/es6/component/Customized'>;
}
declare module 'recharts/es6/component/DefaultLegendContent.js' {
  declare module.exports: $Exports<'recharts/es6/component/DefaultLegendContent'>;
}
declare module 'recharts/es6/component/DefaultTooltipContent.js' {
  declare module.exports: $Exports<'recharts/es6/component/DefaultTooltipContent'>;
}
declare module 'recharts/es6/component/Label.js' {
  declare module.exports: $Exports<'recharts/es6/component/Label'>;
}
declare module 'recharts/es6/component/LabelList.js' {
  declare module.exports: $Exports<'recharts/es6/component/LabelList'>;
}
declare module 'recharts/es6/component/Legend.js' {
  declare module.exports: $Exports<'recharts/es6/component/Legend'>;
}
declare module 'recharts/es6/component/ResponsiveContainer.js' {
  declare module.exports: $Exports<'recharts/es6/component/ResponsiveContainer'>;
}
declare module 'recharts/es6/component/Text.js' {
  declare module.exports: $Exports<'recharts/es6/component/Text'>;
}
declare module 'recharts/es6/component/Tooltip.js' {
  declare module.exports: $Exports<'recharts/es6/component/Tooltip'>;
}
declare module 'recharts/es6/container/Layer.js' {
  declare module.exports: $Exports<'recharts/es6/container/Layer'>;
}
declare module 'recharts/es6/container/Surface.js' {
  declare module.exports: $Exports<'recharts/es6/container/Surface'>;
}
declare module 'recharts/es6/index' {
  declare module.exports: $Exports<'recharts/es6'>;
}
declare module 'recharts/es6/index.js' {
  declare module.exports: $Exports<'recharts/es6'>;
}
declare module 'recharts/es6/numberAxis/Funnel.js' {
  declare module.exports: $Exports<'recharts/es6/numberAxis/Funnel'>;
}
declare module 'recharts/es6/polar/Pie.js' {
  declare module.exports: $Exports<'recharts/es6/polar/Pie'>;
}
declare module 'recharts/es6/polar/PolarAngleAxis.js' {
  declare module.exports: $Exports<'recharts/es6/polar/PolarAngleAxis'>;
}
declare module 'recharts/es6/polar/PolarGrid.js' {
  declare module.exports: $Exports<'recharts/es6/polar/PolarGrid'>;
}
declare module 'recharts/es6/polar/PolarRadiusAxis.js' {
  declare module.exports: $Exports<'recharts/es6/polar/PolarRadiusAxis'>;
}
declare module 'recharts/es6/polar/Radar.js' {
  declare module.exports: $Exports<'recharts/es6/polar/Radar'>;
}
declare module 'recharts/es6/polar/RadialBar.js' {
  declare module.exports: $Exports<'recharts/es6/polar/RadialBar'>;
}
declare module 'recharts/es6/polar/types.js' {
  declare module.exports: $Exports<'recharts/es6/polar/types'>;
}
declare module 'recharts/es6/shape/Cross.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Cross'>;
}
declare module 'recharts/es6/shape/Curve.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Curve'>;
}
declare module 'recharts/es6/shape/Dot.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Dot'>;
}
declare module 'recharts/es6/shape/Polygon.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Polygon'>;
}
declare module 'recharts/es6/shape/Rectangle.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Rectangle'>;
}
declare module 'recharts/es6/shape/Sector.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Sector'>;
}
declare module 'recharts/es6/shape/Symbols.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Symbols'>;
}
declare module 'recharts/es6/shape/Trapezoid.js' {
  declare module.exports: $Exports<'recharts/es6/shape/Trapezoid'>;
}
declare module 'recharts/es6/util/CartesianUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/CartesianUtils'>;
}
declare module 'recharts/es6/util/ChartUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/ChartUtils'>;
}
declare module 'recharts/es6/util/Constants.js' {
  declare module.exports: $Exports<'recharts/es6/util/Constants'>;
}
declare module 'recharts/es6/util/CssPrefixUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/CssPrefixUtils'>;
}
declare module 'recharts/es6/util/DataUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/DataUtils'>;
}
declare module 'recharts/es6/util/DetectReferenceElementsDomain.js' {
  declare module.exports: $Exports<'recharts/es6/util/DetectReferenceElementsDomain'>;
}
declare module 'recharts/es6/util/DOMUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/DOMUtils'>;
}
declare module 'recharts/es6/util/Events.js' {
  declare module.exports: $Exports<'recharts/es6/util/Events'>;
}
declare module 'recharts/es6/util/Global.js' {
  declare module.exports: $Exports<'recharts/es6/util/Global'>;
}
declare module 'recharts/es6/util/IfOverflowMatches.js' {
  declare module.exports: $Exports<'recharts/es6/util/IfOverflowMatches'>;
}
declare module 'recharts/es6/util/LogUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/LogUtils'>;
}
declare module 'recharts/es6/util/PolarUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/PolarUtils'>;
}
declare module 'recharts/es6/util/ReactUtils.js' {
  declare module.exports: $Exports<'recharts/es6/util/ReactUtils'>;
}
declare module 'recharts/es6/util/ShallowEqual.js' {
  declare module.exports: $Exports<'recharts/es6/util/ShallowEqual'>;
}
declare module 'recharts/es6/util/types.js' {
  declare module.exports: $Exports<'recharts/es6/util/types'>;
}
declare module 'recharts/lib/cartesian/Area.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/Area'>;
}
declare module 'recharts/lib/cartesian/Bar.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/Bar'>;
}
declare module 'recharts/lib/cartesian/Brush.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/Brush'>;
}
declare module 'recharts/lib/cartesian/CartesianAxis.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/CartesianAxis'>;
}
declare module 'recharts/lib/cartesian/CartesianGrid.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/CartesianGrid'>;
}
declare module 'recharts/lib/cartesian/ErrorBar.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/ErrorBar'>;
}
declare module 'recharts/lib/cartesian/Line.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/Line'>;
}
declare module 'recharts/lib/cartesian/ReferenceArea.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/ReferenceArea'>;
}
declare module 'recharts/lib/cartesian/ReferenceDot.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/ReferenceDot'>;
}
declare module 'recharts/lib/cartesian/ReferenceLine.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/ReferenceLine'>;
}
declare module 'recharts/lib/cartesian/Scatter.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/Scatter'>;
}
declare module 'recharts/lib/cartesian/XAxis.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/XAxis'>;
}
declare module 'recharts/lib/cartesian/YAxis.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/YAxis'>;
}
declare module 'recharts/lib/cartesian/ZAxis.js' {
  declare module.exports: $Exports<'recharts/lib/cartesian/ZAxis'>;
}
declare module 'recharts/lib/chart/AreaChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/AreaChart'>;
}
declare module 'recharts/lib/chart/BarChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/BarChart'>;
}
declare module 'recharts/lib/chart/ComposedChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/ComposedChart'>;
}
declare module 'recharts/lib/chart/FunnelChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/FunnelChart'>;
}
declare module 'recharts/lib/chart/generateCategoricalChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/generateCategoricalChart'>;
}
declare module 'recharts/lib/chart/LineChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/LineChart'>;
}
declare module 'recharts/lib/chart/PieChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/PieChart'>;
}
declare module 'recharts/lib/chart/RadarChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/RadarChart'>;
}
declare module 'recharts/lib/chart/RadialBarChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/RadialBarChart'>;
}
declare module 'recharts/lib/chart/Sankey.js' {
  declare module.exports: $Exports<'recharts/lib/chart/Sankey'>;
}
declare module 'recharts/lib/chart/ScatterChart.js' {
  declare module.exports: $Exports<'recharts/lib/chart/ScatterChart'>;
}
declare module 'recharts/lib/chart/Treemap.js' {
  declare module.exports: $Exports<'recharts/lib/chart/Treemap'>;
}
declare module 'recharts/lib/component/Cell.js' {
  declare module.exports: $Exports<'recharts/lib/component/Cell'>;
}
declare module 'recharts/lib/component/Customized.js' {
  declare module.exports: $Exports<'recharts/lib/component/Customized'>;
}
declare module 'recharts/lib/component/DefaultLegendContent.js' {
  declare module.exports: $Exports<'recharts/lib/component/DefaultLegendContent'>;
}
declare module 'recharts/lib/component/DefaultTooltipContent.js' {
  declare module.exports: $Exports<'recharts/lib/component/DefaultTooltipContent'>;
}
declare module 'recharts/lib/component/Label.js' {
  declare module.exports: $Exports<'recharts/lib/component/Label'>;
}
declare module 'recharts/lib/component/LabelList.js' {
  declare module.exports: $Exports<'recharts/lib/component/LabelList'>;
}
declare module 'recharts/lib/component/Legend.js' {
  declare module.exports: $Exports<'recharts/lib/component/Legend'>;
}
declare module 'recharts/lib/component/ResponsiveContainer.js' {
  declare module.exports: $Exports<'recharts/lib/component/ResponsiveContainer'>;
}
declare module 'recharts/lib/component/Text.js' {
  declare module.exports: $Exports<'recharts/lib/component/Text'>;
}
declare module 'recharts/lib/component/Tooltip.js' {
  declare module.exports: $Exports<'recharts/lib/component/Tooltip'>;
}
declare module 'recharts/lib/container/Layer.js' {
  declare module.exports: $Exports<'recharts/lib/container/Layer'>;
}
declare module 'recharts/lib/container/Surface.js' {
  declare module.exports: $Exports<'recharts/lib/container/Surface'>;
}
declare module 'recharts/lib/index' {
  declare module.exports: $Exports<'recharts/lib'>;
}
declare module 'recharts/lib/index.js' {
  declare module.exports: $Exports<'recharts/lib'>;
}
declare module 'recharts/lib/numberAxis/Funnel.js' {
  declare module.exports: $Exports<'recharts/lib/numberAxis/Funnel'>;
}
declare module 'recharts/lib/polar/Pie.js' {
  declare module.exports: $Exports<'recharts/lib/polar/Pie'>;
}
declare module 'recharts/lib/polar/PolarAngleAxis.js' {
  declare module.exports: $Exports<'recharts/lib/polar/PolarAngleAxis'>;
}
declare module 'recharts/lib/polar/PolarGrid.js' {
  declare module.exports: $Exports<'recharts/lib/polar/PolarGrid'>;
}
declare module 'recharts/lib/polar/PolarRadiusAxis.js' {
  declare module.exports: $Exports<'recharts/lib/polar/PolarRadiusAxis'>;
}
declare module 'recharts/lib/polar/Radar.js' {
  declare module.exports: $Exports<'recharts/lib/polar/Radar'>;
}
declare module 'recharts/lib/polar/RadialBar.js' {
  declare module.exports: $Exports<'recharts/lib/polar/RadialBar'>;
}
declare module 'recharts/lib/polar/types.js' {
  declare module.exports: $Exports<'recharts/lib/polar/types'>;
}
declare module 'recharts/lib/shape/Cross.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Cross'>;
}
declare module 'recharts/lib/shape/Curve.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Curve'>;
}
declare module 'recharts/lib/shape/Dot.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Dot'>;
}
declare module 'recharts/lib/shape/Polygon.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Polygon'>;
}
declare module 'recharts/lib/shape/Rectangle.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Rectangle'>;
}
declare module 'recharts/lib/shape/Sector.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Sector'>;
}
declare module 'recharts/lib/shape/Symbols.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Symbols'>;
}
declare module 'recharts/lib/shape/Trapezoid.js' {
  declare module.exports: $Exports<'recharts/lib/shape/Trapezoid'>;
}
declare module 'recharts/lib/util/CartesianUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/CartesianUtils'>;
}
declare module 'recharts/lib/util/ChartUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/ChartUtils'>;
}
declare module 'recharts/lib/util/Constants.js' {
  declare module.exports: $Exports<'recharts/lib/util/Constants'>;
}
declare module 'recharts/lib/util/CssPrefixUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/CssPrefixUtils'>;
}
declare module 'recharts/lib/util/DataUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/DataUtils'>;
}
declare module 'recharts/lib/util/DetectReferenceElementsDomain.js' {
  declare module.exports: $Exports<'recharts/lib/util/DetectReferenceElementsDomain'>;
}
declare module 'recharts/lib/util/DOMUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/DOMUtils'>;
}
declare module 'recharts/lib/util/Events.js' {
  declare module.exports: $Exports<'recharts/lib/util/Events'>;
}
declare module 'recharts/lib/util/Global.js' {
  declare module.exports: $Exports<'recharts/lib/util/Global'>;
}
declare module 'recharts/lib/util/IfOverflowMatches.js' {
  declare module.exports: $Exports<'recharts/lib/util/IfOverflowMatches'>;
}
declare module 'recharts/lib/util/LogUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/LogUtils'>;
}
declare module 'recharts/lib/util/PolarUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/PolarUtils'>;
}
declare module 'recharts/lib/util/ReactUtils.js' {
  declare module.exports: $Exports<'recharts/lib/util/ReactUtils'>;
}
declare module 'recharts/lib/util/ShallowEqual.js' {
  declare module.exports: $Exports<'recharts/lib/util/ShallowEqual'>;
}
declare module 'recharts/lib/util/types.js' {
  declare module.exports: $Exports<'recharts/lib/util/types'>;
}
declare module 'recharts/umd/Recharts.js' {
  declare module.exports: $Exports<'recharts/umd/Recharts'>;
}
declare module 'recharts/umd/Recharts.min.js' {
  declare module.exports: $Exports<'recharts/umd/Recharts.min'>;
}
